# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chipping_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('9 Iron', '9 Iron'), ('Pitch Wedge 45', 'Pitching Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58')], max_length=20)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
                ('area', models.CharField(choices=[('CS', 'Center Face Hit'), ('CX', 'Chipping Direction'), ('CD', 'Chipping Distance')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hybrids_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('3 Hybrid', '3 Hybrid')], max_length=15)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
                ('area', models.CharField(choices=[('CS', 'Center Face Hit'), ('DL', 'Divot Location'), ('CP', 'Club Face and Path')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Irons_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('5 Iron', '5 Iron'), ('6 Iron', '6 Iron'), ('7 Iron', '7 Iron'), ('8 Iron', '8 Iron'), ('9 Iron', '9 Iron')], max_length=15)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
                ('area', models.CharField(choices=[('CS', 'Center Face Hit'), ('DL', 'Divot Location'), ('CP', 'Club Face and Path')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Putting_Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('shots_hit', models.IntegerField()),
                ('drill', models.CharField(choices=[('HTH', 'Heel and Toe Hits'), ('3IH', 'Hit to 3 Inch Hole'), ('2IH', 'Hit to 2 Inch Hole')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Putting_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
                ('area', models.CharField(choices=[('PS', 'Putting Speed'), ('PL', 'Putting Line')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wedges_Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('Pitch Wedge 45', 'Pitching Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58')], max_length=20)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('shots_hit', models.IntegerField()),
                ('drill', models.CharField(choices=[('HTH', 'Heel and Toe Hits'), ('TFH', 'High and Low Face Hits'), ('WSG', 'Weak and Strong Grip')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wedges_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('Pitch Wedge 45', 'Pitching Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58')], max_length=20)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
                ('area', models.CharField(choices=[('CS', 'Center Face Hit'), ('WX', 'Wedge Direction'), ('WD', 'Wedge Distance'), ('DL', 'Divot Location')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Woods_Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('Driver', 'Driver'), ('3 Wood', 'Three Wood')], max_length=15)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('shots_hit', models.IntegerField()),
                ('drill', models.CharField(choices=[('HTH', 'Heel and Toe Hits'), ('TFH', 'High and Low Face Hits'), ('WSG', 'Weak and Strong Grip')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Woods_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('Driver', 'Driver'), ('3 Wood', 'Three Wood')], max_length=15)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
                ('area', models.CharField(choices=[('CS', 'Center Face Hit'), ('AA', 'Upward Angle of Attack'), ('CP', 'Club Face and Path')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Woods_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balls_hit', models.IntegerField(default=20)),
                ('center_strike', models.CharField(choices=[('TH', 'Toe Hit'), ('CH', 'Center Hit'), ('HH', 'Heel Hit')], max_length=15)),
                ('angle_of_attack', models.CharField(choices=[('UA', 'Up Angle Hit'), ('LA', 'Flat Angle Hit'), ('DA', 'Downward Angle Hit')], max_length=15)),
                ('club_face_path', models.CharField(choices=[('MS', 'Straight Shot'), ('HS', 'Hook Shot'), ('SS', 'Slice Shot')], max_length=15)),
            ],
        ),
    ]
