# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('Driver', 'Driver'), ('3 Wood', '3 Wood'), ('3 Hybrid', '3 Hybrid'), ('5 Iron', '5 Iron'), ('6 Iron', '6 Iron'), ('7 Iron', '7 Iron'), ('8 Iron', '8 Iron'), ('9 Iron', '9 Iron'), ('Pitch Wedge 45', 'Pitch Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58'), ('Putter', 'Putter')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass_Fail_Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('balls_hit', models.IntegerField()),
                ('balls_succesful', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Range.Club', to_field='club')),
            ],
        ),
        migrations.CreateModel(
            name='Practice_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_area', models.CharField(choices=[('Woods', 'Woods'), ('Hybrids', 'Hybrids'), ('Irons', 'Irons'), ('Wedges', 'Wedges'), ('Chipping', 'Chipping'), ('Putting', 'Putting')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pass_fail_drill',
            name='practice_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Range.Practice_Area', to_field='practice_area'),
        ),
    ]
