# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_area',
            name='practice_area',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Experimental', 'Experimental'), ('Calibration', 'Calibration'), ('Performance', 'Performance'), ('Routine and Games', 'Routine and Games'), ('Test', 'Test')], max_length=50, unique=True),
        ),
    ]
