# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irons_Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('5 Iron', '5 Iron'), ('6 Iron', '6 Iron'), ('7 Iron', '7 Iron'), ('8 Iron', '8 Iron'), ('9 Iron', '9 Iron')], max_length=15)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('shots_hit', models.IntegerField()),
                ('drill', models.CharField(choices=[('HTH', 'Heel and Toe Hits'), ('TFH', 'High and Low Face Hits'), ('WSG', 'Weak and Strong Grip')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
