# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0002_auto_20170607_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_fail_drill',
            name='club',
            field=models.CharField(choices=[('Driver', 'Driver'), ('3 Wood', '3 Wood'), ('3 Hybrid', '3 Hybrid'), ('5 Iron', '5 Iron'), ('6 Iron', '6 Iron'), ('7 Iron', '7 Iron'), ('8 Iron', '8 Iron'), ('9 Iron', '9 Iron'), ('Pitch Wedge 45', 'Pitch Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58'), ('Putter', 'Putter')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pass_fail_drill',
            name='practice_area',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Experimental', 'Experimental'), ('Calibration', 'Calibration'), ('Performance', 'Performance'), ('Routine and Games', 'Routine and Games'), ('Test', 'Test')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Practice_Area',
        ),
    ]
