# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0002_irons_experimental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipping_Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('9 Iron', '9 Iron'), ('Pitch Wedge 45', 'Pitching Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58')], max_length=20)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('shots_hit', models.IntegerField()),
                ('drill', models.CharField(choices=[('RAC', 'One Arm Chip')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hybrids_Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('3 Hybrid', '3 Hybrid')], max_length=15)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('shots_hit', models.IntegerField()),
                ('drill', models.CharField(choices=[('HTH', 'Heel and Toe Hits'), ('TFH', 'High and Low Face Hits'), ('WSG', 'Weak and Strong Grip')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
