# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0003_auto_20170607_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_fail_drill',
            name='practice_area',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Experimental', 'Experimental'), ('Calibration', 'Calibration'), ('Performance', 'Performance'), ('Routine and Games', 'Routine and Games'), ('Test', 'Test')], default='Technical', max_length=25),
        ),
    ]
