# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0003_chipping_experimental_hybrids_experimental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill_Base_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phase', models.CharField(choices=[('Testing', 'Testing'), ('Direct Technical', 'Direct Technical'), ('Experimental', 'Experimental'), ('Calibration', 'Calibration'), ('Performance', 'Performance'), ('Routine and Games', 'Routine and Games')], max_length=25)),
                ('detail', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('drill', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('club', models.CharField(choices=[('Driver', 'Driver'), ('3 Wood', 'Three Wood'), ('3 Hybrid', '3 Hybrid'), ('5 Iron', '5 Iron'), ('6 Iron', '6 Iron'), ('7 Iron', '7 Iron'), ('8 Iron', '8 Iron'), ('9 Iron', '9 Iron'), ('Pitch Wedge 45', 'Pitching Wedge 45'), ('Gap Wedge 50', 'Gap Wedge 50'), ('Sand Wedge 54', 'Sand Wedge 54'), ('Lob Wedge 58', 'Lob Wedge 58')], max_length=25)),
                ('shots_hit', models.IntegerField()),
                ('shots_success', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chipping_Experimental',
        ),
        migrations.DeleteModel(
            name='Chipping_Technical',
        ),
        migrations.DeleteModel(
            name='Hybrids_Experimental',
        ),
        migrations.DeleteModel(
            name='Hybrids_Technical',
        ),
        migrations.DeleteModel(
            name='Irons_Experimental',
        ),
        migrations.DeleteModel(
            name='Irons_Technical',
        ),
        migrations.DeleteModel(
            name='Putting_Experimental',
        ),
        migrations.DeleteModel(
            name='Putting_Technical',
        ),
        migrations.DeleteModel(
            name='Wedges_Experimental',
        ),
        migrations.DeleteModel(
            name='Wedges_Technical',
        ),
        migrations.DeleteModel(
            name='Woods_Experimental',
        ),
        migrations.DeleteModel(
            name='Woods_Technical',
        ),
        migrations.DeleteModel(
            name='Woods_Test',
        ),
    ]
